Update .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -201,10 +201,10 @@ script:
           if [ -e krb5/src ]; then
               sudo apt-get -yq install bison dejagnu gettext keyutils ldap-utils libldap2-dev libkeyutils-dev python-cjson python-paste python-pyrad slapd tcl-dev tcsh;
           fi;
-          if ! HARNESS_VERBOSE_FAILURE=yes BORING_RUNNER_DIR=$top/boringssl/ssl/test/runner make test; then
-              echo -e '\052\052 FAILED -- MAKE TEST';
-              travis_terminate 1;
-          fi;
+    #      if ! HARNESS_VERBOSE_FAILURE=yes BORING_RUNNER_DIR=$top/boringssl/ssl/test/runner make test; then
+    #          echo -e '\052\052 FAILED -- MAKE TEST';
+    #          travis_terminate 1;
+    #      fi;
       else
           if ! $make build_tests >~/build.log 2>&1; then
               echo -e '\052\052 FAILED -- MAKE BUILD_TESTS';
